from comandos import *
def caminhoCastelo1():
    andar_esquerda_frente(3.5)
    andar_frente(1.2)
    andar_esquerda_frente(6)
    andar_esquerda(1.8)
    andar_esquerda_tras(7)
    andar_tras(1)
    andar_direita_tras(15)

def caminhoCastelo2():
    andar_tras(5)
    andar_esquerda_tras(8)
    andar_tras(4)
    andar_esquerda_tras(4)
    andar_esquerda(1)
    andar_tras(1)
    andar_esquerda_tras(9)
    pyautogui.moveTo(130,209)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    quebrar_portao()
    andar_esquerda_tras(8)
    andar_esquerda(5)

def caminhoCastelo3():
    andar_tras(17)
    andar_esquerda(4)
    andar_esquerda_tras(5)
    andar_tras(5)
    andar_esquerda_tras(5)
    andar_esquerda(5)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_frente(2)
    andar_esquerda_frente(2.8)
    andar_direita(3)
    clique_em(322, 213)
    keyboard.send('1')
    andar_tras(3)
    andar_direita_tras(8)
    andar_direita(2)
    andar_direita_tras(3)

def caminhoCastelo4():
    andar_esquerda(4)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_frente(2)
    andar_esquerda(3)
    andar_frente(1)
    andar_esquerda_frente(2)
    andar_esquerda_tras(2)
    andar_esquerda(3)
    andar_frente(1)
    andar_esquerda(3)

def caminhoCastelo5():
    andar_frente(3)
    andar_direita(0.5)
    andar_direita_frente(13)
    andar_frente(4)
    andar_direita(5)
    andar_direita_tras(10)
    andar_direita(3)
    andar_frente(7)
    clique_em(442,210)
    keyboard.send(3)
    keyboard.send('space')
    andar_tras(3)

def caminhoCastelo6():
    andar_direita(3)
    andar_direita_frente(5)
    andar_frente(7)
    andar_esquerda(6)
    andar_esquerda_tras(5)

def caminhoCastelo7():
    andar_esquerda_frente(3)
    andar_frente(2.7)
    andar_direita_frente(3)    
    andar_esquerda_frente(6)
    andar_esquerda(3.5)
    andar_frente(0.5)
    andar_esquerda_frente(4)
    andar_esquerda(2)

def caminhoCastelo8():
    andar_tras(4)
    andar_esquerda_tras(2)
    andar_tras(6)
    andar_esquerda_tras(9)
    andar_direita_tras(6)
    andar_tras(0.5)
    andar_direita(6)
    clique_em(325,390)
    time.sleep(0.5)
    keyboard.send("space")
    andar_esquerda(4)
    andar_tras(2)

def caminhoCastelo9():
    andar_esquerda_tras(5)
    andar_esquerda(12)
    andar_tras(2)
    andar_direita(3)
    andar_direita_tras(4)
    andar_tras(1)

def caminhoCastelo10():
    time.sleep(1)
    andar_tras(7)
    andar_direita_tras(4)
    andar_tras(6)

def caminhoCastelo11():
    andar_esquerda(3)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_esquerda_frente(5)
    andar_frente(1)
    andar_esquerda_frente(3)
    andar_frente(1)
    andar_esquerda_frente(3)
    andar_esquerda_frente(3)
    andar_tras(0.5)
    andar_esquerda_frente(5)
    andar_frente(5)
    andar_frente(2)
    andar_direita_frente(2)
    andar_direita(3)
    andar_direita_tras(1)
    andar_direita(3)
    andar_direita_frente(3)
    andar_frente(5)

def caminhoCastelo12():
    andar_direita_frente(4)
    andar_direita(2)

def caminhoCastelo13():
    andar_direita(6)
    andar_frente(5)
    andar_direita_frente(5)
    andar_direita(2)
    matar_monstros()
    andar_direita_frente(4)
    andar_frente(2)
    andar_direita_frente(4)
    
def caminhoCastelo14():
    andar_esquerda(4)
    andar_frente(3)
    andar_direita_frente(3)
    andar_direita(2)

    
def altarSiena1SS(gema = False, bp = False, mula = False):
    inicio_pt1()
    inicio_pt2(287, 250)
    if tela_dg():
        dg1()
        while entrada_disponivel(False):
            time.sleep(0.5)
            entrar(False)
            andar_direita_frente(2)
                    
            andar_direita_tras(5)
            clique_em(566,230)
            for i in range(6):
                keyboard.send('space')
            clique_em(100,465, False)
            andar_direita_frente(2)
            andar_direita_tras(5)
            procurar_boss()
            matar_boss("bm3")
            quebrar_bau("bau")
            andar_direita_frente(2)
            andar_direita_tras(5)
            andar_esquerda_tras(6)
            andar_esquerda_frente(6)
            andar_direita_frente(2)
            clique_em(400, 120, False)
            keyboard.send('space')
            andar_direita_frente(8)
            clique_em(383, 233, False)
            for i in range(6):
                keyboard.send('space')
            andar_esquerda_tras(5)
            andar_direita_tras(7)
            andar_esquerda_tras(2)
            andar_direita_tras(5)
            andar_direita(2)
            clique_em(400,400)
            for i in range(6):
                keyboard.send('space')
            andar_esquerda_frente(5)
            andar_direita_frente(0.8)
            andar_esquerda_frente(5)
            andar_direita_frente(6)
            andar_esquerda_tras(0.3)
            andar_direita_tras(3)
            clique_em(460,440)
            keyboard.send('space')
            andar_esquerda_frente(3)
            andar_esquerda_tras(3)
            andar_esquerda_frente(3)
            andar_esquerda_tras(5)
            andar_esquerda_frente(3)
            andar_direita_frente(0.3)
            andar_frente(3)
            andar_direita(2)
            andar_frente(0.7)
            andar_direita_frente(4)
            procurar_boss()
            matar_boss("bm3")
            andar_esquerda_frente(2)
            andar_direita_tras(0.5)
            andar_direita_frente(6)
            andar_esquerda_tras(0.3)
            andar_direita_tras(10)
            quebrar_bau("reliquia")
            andar_direita_tras(3)
            andar_esquerda_tras(7)
            andar_direita_tras(5)
            andar_esquerda_frente(0.3)
            andar_direita_frente(5)
            andar_esquerda_tras(0.3)
            andar_esquerda_frente(3)
            andar_direita_frente(3)
            andar_direita_tras(13)