from comandos import *
from asa import asa_caminho1
from  DGs.ilhaProibida import ilhaProibida
from  DGs.altarSiena1SS import altarSiena1SS
from DGs.selo import selo
from rodar import rodar
from dxd import *
from DGs.DX.morada_das_chamas_desperto import *
from DGs.DX.valeTempestuoso import *
from DGs.DX.catacumbaGelida import *
from DGs.DXD.locomotivaLouca import *
from arena_do_eterno import *
from DGs.castelo_das_ilusoes import *
from up_sn_capella import *
from DGs.tg import *

bp = False
mula = False
def entrar_canal_5():
    time.sleep(1)
    pyautogui.moveTo(669, 479)
    time.sleep(1)
    pyautogui.rightClick()
    while(1):
        pyautogui.moveTo(430, 343)
        time.sleep(0.2)
        pyautogui.click()
            
def teste_comandos():
    pyautogui.moveTo(600, 479)
    time.sleep(2)
    pyautogui.click()
    time.sleep(2)
    print("keyboard send")
    for i in range(10):
        keyboard.send("e")
        time.sleep(0.5)
    print("keyboard press")
    keyboard.press("d")
    time.sleep(2)
    keyboard.send("d")
    print("keyboard press and release")
    keyboard.press_and_release("w")
    time.sleep(2)
    keyboard.send("w")
    print("keyboard on press")
    keyboard.on_press("q")
    time.sleep(2)
    keyboard.send("q")
    print("keyboard on press key")
    keyboard.on_press_key("s")
    time.sleep(2)
    keyboard.send("s")
    print("keyboard hook key")
    keyboard.hook_key("e")
    time.sleep(2)
    keyboard.send("e")
    print("keyboard is pressed")
    keyboard.is_pressed("w")
    time.sleep(2)
    keyboard.send("w")
    print("pyautogui hold")
    pyautogui.hold("q")
    time.sleep(2)
    keyboard.send("q")
    print("pyautogui hotkey")
    pyautogui.hotkey("s")
    time.sleep(2)
    keyboard.send("s")
    print("pyautogui keydown")
    pyautogui.keyDown("e")
    time.sleep(2)
    pyautogui.keyUp("e")
    keyboard.send("e")
    print("pyautogui press")
    pyautogui.press("w")
    time.sleep(2)
    keyboard.send("w")
    
    
    
            
def teste():
    
    time.sleep(1)
    pyautogui.moveTo(669, 479)
    time.sleep(1)
    pyautogui.rightClick()
    tg3()
    # b2f
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('space')
    # time.sleep(1)
    # for i in range(3):
    #     matar_monstro_ate_boss()
    #     matar_boss('no')
    # quebrar_bau('bau')
    # andar_direita_frente(11)
    # andar_esquerda_frente(10)
    # matar_monstro_ate_boss()
    # matar_boss('no')
    # quebrar_bau('reliquia')
    # andar_tras(1)
    # andar_esquerda(12)
    # matar_monstro_ate_boss()
    # matar_boss('no')
    # quebrar_bau('bau')
    # andar_esquerda_tras(12)
    # clique_em(320, 200, True)
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('space')
    # time.sleep(1)
    # andar_esquerda_frente(2)
    # matar_monstro_ate_boss()
    # matar_boss('no')
    # quebrar_bau('reliquia')
    # andar_esquerda_frente(16)
    # andar_esquerda_tras(20)
            
    # vale tempestuoso
    # time.sleep(0.5)
    # andar_tras(4)
    # andar_esquerda(2)
    # andar_esquerda_frente(3)
    # matar_monstros()
    # andar_direita_tras(8)
    # andar_direita(1)
    # andar_frente(2)
    # matar_boss("nobm")
    # time.sleep(0.5)
    # quebrar_bau("bau")
    # finalizar(bp, mula)
    # resgatar_presente()
    # preparacao()
    # pyautogui.moveTo(198, 200)
    # time.sleep(2)
    # pyautogui.click()
    # dg4()
    
    
    
    
    # andar_direita_tras(9)
    # andar_direita_frente(2)
    # andar_esquerda_frente(3)
    # andar_frente(4)
    # andar_direita_tras(5)
    # andar_direita(3)
    # andar_direita_tras(2)
    # andar_tras(3)
    # procurar_portao()
    # time.sleep(0.5)
    # quebrar_portao()
    # time.sleep(0.5)
    # procurar_portao()
    # time.sleep(0.5)
    # quebrar_portao()
    # time.sleep(0.5)
    # andar_direita_tras(6)
    # time.sleep(0.5)
    # procurar_portao()
    # time.sleep(0.5)
    # quebrar_portao()
    # time.sleep(0.5)
    # clique_em(530, 370, False)
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('space')
    # time.sleep(0.5)
    # andar_direita_tras(6)
    # procurar_boss()
    # matar_boss('no')
    # time.sleep(0.5)
    # quebrar_bau('bau')
    # time.sleep(1)
    # andar_direita_tras(5)
    # andar_direita(1)
    # clique_em(400, 265, False)
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('space')
    # andar_esquerda_tras(5)
    # andar_direita_tras(2)
    # andar_direita(1)
    # andar_direita_tras(3)
    # andar_direita(1)
    # andar_direita_tras(3)
    # procurar_boss()
    # matar_boss('no')
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('z')
    #     time.sleep(0.5)
    #     atacar()
    # andar_frente(2)
    # andar_esquerda_tras(1)
    # andar_tras(2)
    # andar_direita_tras(17)
    # andar_frente(3)
    # andar_esquerda_frente(3)
    # procurar_portao()
    # quebrar_portao()
    # andar_direita_frente(3)
    # andar_frente(2)
    # andar_esquerda_frente(1)
    # matar_monstro_ate_boss()    
    # matar_boss('no')
    # quebrar_bau('bau')
    # andar_frente(4)
    # clique_em(452, 224, False)
    # for i in range(5):
    #     time.sleep(0.5)
    #     keyboard.send('space')
    # clique_em(108, 465, False)
    # passar_portal(5)
    # andar_direita(2)
    # andar_frente(4)
    # andar_direita_frente(2)
    # andar_direita_tras(13)
    # andar_esquerda_tras(2)
    # procurar_portao()
    # quebrar_portao()
    # andar_esquerda_tras(8)
    # andar_direita_tras(5)
    # procurar_boss()
    # matar_boss('no')
    # quebrar_bau('bau')
    # andar_direita_tras(6)
    # andar_frente(8)
    # clique_em(500, 345, False)
    # passar_portal(5)
    # andar_direita_tras(5)
    # procurar_boss()
    # matar_boss('no')
    # quebrar_bau('bau')
    # andar_esquerda_frente(3)
    # clique_em(340, 200, False)
    # passar_portal(5)
    # andar_esquerda_tras(2)
    # andar_tras(1)
    # andar_direita_tras(12)
    # andar_direita(4)
    
        
    # entrar_canal_5()
    # for i in range(100):
    #     rodar()
    # catacumba_gelida(dificuldade="premium")

    # while(True):
    #     up_sn()
           
    # matar_monstros()
    # andar_direita_frente(5)
    # andar_direita(5)
    # matar_monstros()
    # andar_direita(3)
    # clique_em()
# teste()