from PIL import Image, ImageTk

caminho = "c:\\mccb"

img_entrar = Image.open(caminho + "\\imgs\\entrar.png")
img_entrar2 = Image.open(caminho + "\\imgs\\entrar2.png")
menino_img = Image.open(caminho + "\\imgs\\menino_misterioso.png")
monstros = Image.open(caminho + "\\imgs\\mobs.png")
img_bau_reliquia = Image.open(caminho + "\\imgs\\bau_da_reliquia.png")
img_bau = Image.open(caminho + "\\imgs\\bau.png")
imgBauTesouro = Image.open(caminho + "\\imgs\\bauTesouro.png")
img_bau_legendario = Image.open(caminho + "\\imgs\\bau_da_legendario.png")
img_bau_legado = Image.open(caminho + "\\imgs\\bau_do_legado.png")
boss = Image.open(caminho + "\\imgs\\boss.png")
fechar_img = Image.open(caminho + "\\imgs\\fechar.png")
dg_finalizada_img = Image.open(caminho + "\\imgs\\dg_finalizada.png")
entrar_gemas_2_img = Image.open(caminho + "\\imgs\\entrar_gema_2.png")
sp = Image.open(caminho + "\\imgs\\sp.png")
img_sp_full = Image.open(caminho + "\\imgs\\sp_full.png")
img_dg_falhou = Image.open(caminho + "\\imgs\\dg_falhou.png")
img_espera = Image.open(caminho + "\\imgs\\espera.png")
boss = Image.open(caminho + "\\imgs\\boss.png")
sp_final = Image.open(caminho + "\\imgs\\sp_final.png")
img_tela_dg = Image.open(caminho + "\\imgs\\tela_dg.png")
img_tela_dg2 = Image.open(caminho + "\\imgs\\tela_dg2.png")
elite = Image.open(caminho + "\\imgs\\elite.png")
img_bm3_ma = Image.open(caminho + "\\imgs\\bm3_ma.png")
img_gigante = Image.open(caminho + "\\imgs\\gigante.png")
img_boto_cruel = Image.open(caminho + "\\imgs\\boto_cruel.png")
img_morreu = Image.open(caminho + "\\imgs\\morreu.png")
img_morreu2 = Image.open(caminho + "\\imgs\\morreu2.png")
img_portao = Image.open(caminho + "\\imgs\\portao.png")
img_perdeu_hp = Image.open(caminho + "\\imgs\\perdeu_hp.png")
img_muchaa = Image.open(caminho + "\\imgs\\muchaa.png")
img_portao_morada_d = Image.open(caminho + "\\imgs\\portao_morada_d.png")
img_plus = Image.open(caminho + "\\imgs\\plus.png")
img_plus2 = Image.open(caminho + "\\imgs\\plus2.png")
img_plus3 = Image.open(caminho + "\\imgs\\plus3.png")
img_urso = Image.open(caminho + "\\imgs\\urso.png")
img_golemjr = Image.open(caminho + "\\imgs\\golemjr.png")
img_espirito_da_lava = Image.open(caminho + "\\imgs\\espirito_da_lava.png")
img_asa_verde = Image.open(caminho + "\\imgs\\asa_verde.png")
img_tela_npc = Image.open(caminho + "\\imgs\\tela_npc.png")
img_pilha_de_ossos_congelados = Image.open(caminho + "\\imgs\\pilha_de_ossos_congelados.png")
img_sleak = Image.open(caminho + "\\imgs\\sleak.png")
imgLobyTg = Image.open(caminho + "\\imgs\\lobyTg.png")
img_portao_monstro = Image.open(caminho + "\\imgs\\portao_monstro.png")
imgClasseMa = Image.open(caminho + "\\imgs\\classeMa.png")



