from comandos import *
def caminhoCastelo1():
    andar_esquerda_frente(3.5)
    andar_frente(1.2)
    andar_esquerda_frente(6)
    andar_esquerda(1.8)
    andar_esquerda_tras(7)
    andar_tras(1)
    andar_direita_tras(15)

def caminhoCastelo2():
    andar_tras(5)
    andar_esquerda(1.2)
    andar_esquerda_tras(8)
    andar_tras(8)
    andar_esquerda(4)
    andar_tras(1)
    andar_esquerda_tras(9)
    pyautogui.moveTo(130,209)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    quebrar_portao()
    andar_esquerda_tras(8)
    andar_esquerda(5)

def caminhoCastelo3():
    andar_tras(17)
    andar_esquerda(4)
    andar_esquerda_tras(5)
    andar_tras(5)
    andar_esquerda_tras(5)
    andar_esquerda(5)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_frente(2)
    andar_esquerda_frente(2.8)
    andar_direita(3)
    clique_em(322, 213)
    keyboard.send('1')
    andar_tras(3)
    andar_direita_tras(8)
    andar_direita(2)
    andar_direita_tras(3)

def caminhoCastelo4():
    andar_esquerda(4)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_frente(2)
    andar_esquerda(3)
    andar_frente(1)
    andar_esquerda_frente(2)
    andar_esquerda_tras(2)
    andar_esquerda(3)
    andar_frente(1)
    andar_esquerda(3)

def caminhoCastelo5():
    andar_frente(3)
    andar_direita(0.5)
    andar_direita_frente(13)
    andar_frente(4)
    andar_direita(5)
    andar_direita_tras(10)
    andar_direita(3)
    andar_frente(7)
    clique_em(442,210)
    keyboard.send(3)
    keyboard.send('space')
    andar_tras(3)

def caminhoCastelo6():
    andar_direita(3)
    andar_direita_frente(5)
    andar_frente(7)
    andar_esquerda(6)
    andar_esquerda_tras(5)

def caminhoCastelo7():
    andar_esquerda_frente(3)
    andar_frente(2.7)
    andar_direita_frente(3)    
    andar_esquerda_frente(6)
    andar_esquerda(3.5)
    andar_frente(0.5)
    andar_esquerda_frente(4)
    andar_esquerda(2)

def caminhoCastelo8():
    andar_tras(4)
    andar_esquerda_tras(2)
    andar_tras(6)
    andar_esquerda_tras(9)
    andar_direita_tras(6)
    andar_tras(0.5)
    andar_direita(6)
    clique_em(325,390)
    time.sleep(0.5)
    keyboard.send("space")
    andar_esquerda(4)
    andar_tras(2)

def caminhoCastelo9():
    andar_esquerda_tras(5)
    andar_esquerda(12)
    andar_tras(2)
    andar_direita(3)
    andar_direita_tras(4)
    andar_tras(1)

def caminhoCastelo10():
    time.sleep(1)
    andar_tras(7)
    andar_direita_tras(4)
    andar_tras(6)

def caminhoCastelo11():
    andar_esquerda(3)
    andar_esquerda_frente(4)
    andar_esquerda(3)
    andar_esquerda_frente(5)
    andar_frente(1)
    andar_esquerda_frente(3)
    andar_frente(1)
    andar_esquerda_frente(3)
    andar_esquerda_frente(3)
    andar_tras(0.5)
    andar_esquerda_frente(5)
    andar_frente(5)
    andar_frente(2)
    andar_direita_frente(2)
    andar_direita(3)
    andar_direita_tras(1)
    andar_direita(3)
    andar_direita_frente(3)
    andar_frente(5)

def caminhoCastelo12():
    andar_direita_frente(4)
    andar_direita(2)

def caminhoCastelo13():
    andar_direita(6)
    andar_frente(5)
    andar_direita_frente(5)
    andar_direita(2)
    matar_monstros()
    andar_direita_frente(4)
    andar_frente(2)
    andar_direita_frente(4)
    
def caminhoCastelo14():
    andar_esquerda(4)
    andar_frente(3)
    andar_direita_frente(3)
    andar_direita(2)

    
def b1f(gema = False, bp = False, mula = False):
    inicio_pt1()
    andar_frente(2)
    inicio_pt2(390, 230)
    if tela_dg():
        dg1()
        while entrada_disponivel(False):
            time.sleep(0.5)
            entrar(False)
            while not tem_monstro_especifico(img_portao):
                andar_esquerda_frente(3.5)
                matar_monstros()
                andar_esquerda_frente(9)
                andar_direita_frente(3)
                clique_em(468, 177, False)
            quebrar_portao()
            andar_direita_frente(2)
            matar_monstro_ate_boss()
            matar_boss("nobm")
            quebrar_bau("bau")
            time.sleep(1)
    
            while pyautogui.locateOnScreen(img_tela_npc) is None:
                andar_direita_frente(4)
                andar_esquerda(1.5)
                clique_em(560, 95, False)
            time.sleep(0.5)
            keyboard.send("space")
            andar_direita_tras(3)
            matar_monstro_ate_boss()
            matar_boss("nobm")
            time.sleep(0.5)
            quebrar_bau("bau")
            andar_direita_tras(14)
            andar_tras(1)
            andar_direita_tras(2)
            procurar_boss()
            matar_boss("nobm")
            time.sleep(1)
            andar_direita_tras(5)
            quebrar_bau("bau")
            time.sleep(1)
            procurar_boss()
            matar_boss("nobm")
            quebrar_bau("bau")

            while pyautogui.locateOnScreen(img_tela_npc) is None:
                andar_direita_tras(6)
                clique_em(310,212, False)
            time.sleep(0.5)
            keyboard.send("space")
            andar_esquerda_tras(5)
            while tem_monstro_especifico(monstros):
              matar_monstro_especifico(monstros)
              time.sleep(2)
            for i in range(3):
                quebrar_bau("bau")
                
            while not tem_monstro_especifico(img_portao):
                andar_esquerda_tras(20)
                clique_em(320,330, False)
            quebrar_portao()
            andar_esquerda_tras(5)
            for i in range(2):
                if tem_monstro_especifico(elite):
                    matar_elite()
            quebrar_bau("legado")
            andar_esquerda_tras(4)
            procurar_boss()
            matar_boss("nobm")
            for i in range(9):
                keyboard.send("space")
                time.sleep(0.5)
            time.sleep(1)
            quebrar_bau("bau")
            finalizar(bp, mula)
            time.sleep(5)
            resgatar_presente()
            time.sleep(2)
            quebrarItens()
            inicio_pt1()
            andar_frente(2)
            inicio_pt2(390, 230)
            if tela_dg():
                dg1()